## Numpy Array and Basic
learn about numpy with chai or code

In [1]:
import numpy as np

### creating array from list

In [2]:
arr_1d=np.array([1,2,3,4,5,6,7])
print("result of 1D array: ",arr_1d)
arr_2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("result of 1D array: ",arr_2d)

result of 1D array:  [1 2 3 4 5 6 7]
result of 1D array:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### List vs Numpy array

In [3]:
py_List=[1,2,3,4]
print("Python list multiplicatiosn : ",py_List*2)

np_arr=np.array([1,2,3,4,5]) ## element wise multiplications
print("Numpy array multiplicatiosn : ",np_arr*2)

import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n list operations time : ", time.time()-start )

start=time.time()
np_arr=np.arange(100000) *2
print("\n Numpy array operations time : ", time.time()-start )
## numpy array are faster then python list 





Python list multiplicatiosn :  [1, 2, 3, 4, 1, 2, 3, 4]
Numpy array multiplicatiosn :  [ 2  4  6  8 10]

 list operations time :  0.18013715744018555

 Numpy array operations time :  0.0008332729339599609


## Creating array from Scratch

In [4]:
## Naya array banane ka process bina kisi pehle se mojood data ke.

zeros=np.zeros([3,4]) ## 3 rows and 4 column
print(" zeros array:\n ",zeros)

ones=np.ones([3,3])
print(" ones array:\n ", ones)

full=np.full((3,3),69)  ##jo number bhi dain apni marzi sab columns or rows main yeh number ajaiga
print(" full array:\n ",full)

random=np.random.random((3,3))
print(" random array:\n ",random)

sequence=np.arange(0,10,2)
print(" sequence array:\n ",sequence)

 zeros array:
  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 ones array:
  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
 full array:
  [[69 69 69]
 [69 69 69]
 [69 69 69]]
 random array:
  [[0.4371228  0.55010216 0.97247282]
 [0.23658134 0.09567218 0.62420885]
 [0.17103222 0.49781126 0.85793202]]
 sequence array:
  [0 2 4 6 8]


### Vector , Matrix and Tensor

In [5]:
vector=np.array([1,2,3])
print("vector :",vector)

## 2D array ko matrix kehtay hain
matrix=np.array([[1,2,3,],
                 [4,5,6],
                 [7,8,9]])
print("matrix :",matrix)

## ziyada dimensions kaylie Tensor use kartay hai

tensor=np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]]])
print("tensor :",tensor)


vector : [1 2 3]
matrix : [[1 2 3]
 [4 5 6]
 [7 8 9]]
tensor : [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Array Properties 

In [6]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape ",arr.shape)
print("Dimension ",arr.ndim)
print("Size ",arr.size)
print("Dtype ",arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
Dtype  int64


## Array Reshaped

In [7]:
arr=np.arange(12)
print("Range of array" , arr)

reshaped=arr.reshape((3,4))
print("\n Rshape of array" , reshaped)

flattend=reshaped.flatten()
print("\n Flattend of array" , flattend)

#this method give orignal array not give copy array
rave=reshaped.ravel()
print("\n revalf array" ,rave )

# TRANSPOSE ARRAY
trans=reshaped.T
print("Transpose  of array" , trans)




Range of array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Rshape of array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattend of array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 revalf array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose  of array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Numpy Array Operations

In [8]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing  ", arr[4:10])
print("Basic Slicing wiht Steps  ", arr[1:10:2])
print("Basic Slicing with Negative value  ", arr[-4])

Basic Slicing   [ 5  6  7  8  9 10]
Basic Slicing wiht Steps   [ 2  4  6  8 10]
Basic Slicing with Negative value   7


## Sorting

In [9]:
import numpy as np
unsorted = np.array([1,2,9,8,5,4,7,3,6])
print(np.sort(unsorted))

unsorted_2D = np.array([[5,1],[4,2],[1,1]])
print(np.sort(unsorted_2D,axis=1))

[1 2 3 4 5 6 7 8 9]
[[1 5]
 [2 4]
 [1 1]]


## Filtering

In [10]:
import numpy as np
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0 ]
print("Even Numbers ", even_number)

Even Numbers  [ 2  4  6  8 10]


## Filter with mask

In [11]:
mask = numbers > 5
print("Numbers greater then 5", numbers[mask])


Numbers greater then 5 [ 6  7  8  9 10]


## Fancing indexing vs np.where

In [12]:
indicias = [2,4,6]
print(numbers[indicias]) 

where_result = np.where(numbers > 5)
print ("NP where  ", numbers[where_result])

[3 5 7]
NP where   [ 6  7  8  9 10]


In [13]:
condition_array = np.where(numbers > 5, numbers *2,numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


In [14]:
condition_array = np.where(numbers > 5, "True","False")
print(condition_array)

['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


## Adding and removing data 

In [15]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8,9])
combined= np.concatenate((arr1,arr2))


print(combined)


[1 2 3 4 5 5 6 7 8 9]


### array compatibility 

In [16]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12,13])

print("compatibility ", a.shape == b.shape)
print("compatibility ", a.shape == c.shape)

compatibility  True
compatibility  False


In [17]:
original = np.array([[1,2,3],[4,5,6]])
new_row = np.array([7,8,9])

with_new_row = np.vstack((original,new_row))
print(original,"\n")
print(with_new_row,"\n")

new_col = np.array([[11],[12]])
# new_col2 = np.array([[12]])
with_new_col = np.hstack((original,new_col))

print(original,"\n")
print(with_new_col,"\n")


[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2 3]
 [4 5 6]] 

[[ 1  2  3 11]
 [ 4  5  6 12]] 

