Got it — you want a practical-based quiz on NumPy and Pandas for 100 marks total, and the level should be intermediate.
I’ll design it like a real test where students have to code, analyze, and solve practical tasks.

Here’s the full quiz:


---

NumPy and Pandas Intermediate Quiz (Practical Based - 100 Marks)

Section B: Pandas (50 Marks)

Q6. DataFrame Creation and Indexing (10 marks)

Create a DataFrame with the following columns: 'Name', 'Age', 'City', 'Marks'.

Insert at least 6 rows manually.

Set 'Name' as the index.


Q7. Data Cleaning (10 marks)

Introduce 2 NaN values manually in your DataFrame.

Fill the NaN values:

One with a constant value.

One with the mean of the column.



Q8. GroupBy and Aggregation (10 marks)

Using the same or new DataFrame:

Group the data by 'City'.

Find the average 'Marks' for each city.



Q9. Merging and Joining (10 marks)

Create two DataFrames:

One with 'StudentID', 'Name'.

Another with 'StudentID', 'Subject', 'Grade'.


Perform an inner join on 'StudentID'.


Q10. Data Filtering and Sorting (10 marks)

Filter students who have scored marks greater than 80.

Sort the DataFrame in descending order of 'Marks'.



---

Instructions

You must use only NumPy and Pandas (no other libraries unless specified).

Proper comments and clean code will be rewarded with extra marks.

Partial answers will receive partial marks.


Marks Distribution


---

Would you also like me to prepare a solution key separately if needed?
I can even format it into a PDF-style sheet if you want!
Should I continue with that?

Q1. Array Creation and Manipulation (10 marks)

Create a 5×5 NumPy array with random integers from 1 to 50.

Replace all even numbers in the array with -1.


In [1]:
import numpy as np 

In [12]:
df = np.random.randint(1,51,size=(5,5))
df

array([[20, 26, 21,  6, 22],
       [50, 19, 33, 39,  2],
       [ 3, 17, 23, 39,  1],
       [45, 42, 17,  1,  1],
       [19,  5, 49, 15,  4]], dtype=int32)

In [22]:
df[ i % 2 == 0] = -1
df

array([[-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [ 3, 17, 23, 39,  1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1]], dtype=int32)


Q2. Statistical Operations (10 marks)

Given a random array of size 100, calculate:

Mean

Median

Standard deviation

Variance


In [30]:
arr = np.random.randint(1,101, size=(1,100))
print(arr.mean())
print(arr.std())
print(arr.var())

48.76
30.220562536127616
913.2823999999999



Q3. Array Reshaping (10 marks)

Create a 1D array of 30 elements.

Reshape it into a 3D array with shape (3, 2, 5).

Swap the axes of the 3D array.


In [47]:
arr = np.random.randint(1,100,size=(30))
redhape_3D =arr.reshape(3,2,5)
redhape_3D


array([[[65, 59, 41,  6,  2],
        [56, 43, 85, 29, 94]],

       [[ 1,  9,  9, 46, 31],
        [42, 57,  7, 50, 48]],

       [[40, 53, 51, 49, 42],
        [60,  7, 43, 44, 42]]], dtype=int32)

In [48]:
x= np.swapaxes(redhape_3D,1,2) # swapping axis 0 and axis 1
x

array([[[65, 56],
        [59, 43],
        [41, 85],
        [ 6, 29],
        [ 2, 94]],

       [[ 1, 42],
        [ 9, 57],
        [ 9,  7],
        [46, 50],
        [31, 48]],

       [[40, 60],
        [53,  7],
        [51, 43],
        [49, 44],
        [42, 42]]], dtype=int32)



Q4. Broadcasting and Vectorization (10 marks)

Create two arrays:

Array A of shape (5,1)

Array B of shape (1,5)


Add them together using broadcasting.


In [49]:
a = np.random.randint(1,50,size=(5,1))
b = np.random.randint(1,50,size=(1,5))

result = a + b
result

array([[30, 23, 29, 15, 20],
       [55, 48, 54, 40, 45],
       [73, 66, 72, 58, 63],
       [34, 27, 33, 19, 24],
       [53, 46, 52, 38, 43]], dtype=int32)


Q5. Logical Operations and Indexing (10 marks)

Create an array of numbers from 10 to 50.

Extract all numbers that are divisible by both 3 and 5.


In [70]:
arr = np.random.randint(10,50,size=(5,5))
arr

array([[40, 25, 10, 24, 21],
       [38, 25, 12, 13, 22],
       [30, 38, 24, 38, 19],
       [42, 40, 36, 20, 18],
       [31, 23, 32, 38, 34]], dtype=int32)

In [71]:
x = arr[(arr % 3 == 0) &( arr % 5 == 0)]
print(x)


[30]
