## Numpy Array and operation

In [1]:
import numpy as np 

arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing", arr[1:5])
print("With Step", arr[2:8:2])
print("Negative Indexing", arr[-8])


Basic Slicing [2 3 4 5]
With Step [3 5 7]
Negative Indexing 2


In [2]:
import numpy as np
arr_2d=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print("Slicing in 2D array:",arr_2d[1,2])
print("Slicing in 2D array:",arr_2d[:,1])
print("Slicing in 2D array:",arr_2d[0,1])



Slicing in 2D array: 6
Slicing in 2D array: [2 5 8]
Slicing in 2D array: 2


## Sorting

In [4]:
import numpy as np
unsorted = np.array([1,2,9,8,5,4,7,3,6])
print(np.sort(unsorted))

unsorted_2D = np.array([[5,1],[4,2],[1,1]])
print(np.sort(unsorted_2D,axis=1))

[1 2 3 4 5 6 7 8 9]
[[1 5]
 [2 4]
 [1 1]]


## Filtering

In [5]:
import numpy as np
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0 ]
print("Even Numbers ", even_number)

Even Numbers  [ 2  4  6  8 10]


## Filter with mask

In [7]:
mask = numbers > 5
print("Numbers greater then 5", numbers[mask])


Numbers greater then 5 [ 6  7  8  9 10]


## Fancing indexing vs np.where

In [9]:
indicias = [2,4,6]
print(numbers[indicias]) 

where_result = np.where(numbers > 5)
print ("NP where  ", numbers[where_result])

[3 5 7]
NP where   [ 6  7  8  9 10]


In [14]:
condition_array = np.where(numbers > 5, numbers *2,numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


In [11]:
condition_array = np.where(numbers > 5, "True","False")
print(condition_array)

['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


## Adding and removing data 

In [5]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8,9])
combined= np.concatenate((arr1,arr2))


print(combined)


[1 2 3 4 5 5 6 7 8 9]


### array compatibility 

In [18]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12,13])

print("compatibility ", a.shape == b.shape)
print("compatibility ", a.shape == c.shape)

compatibility  True
compatibility  False


In [22]:
original = np.array([[1,2,3],[4,5,6]])
new_row = np.array([7,8,9])

with_new_row = np.vstack((original,new_row))
print(original,"\n")
print(with_new_row,"\n")

new_col = np.array([[11],[12]])
# new_col2 = np.array([[12]])
with_new_col = np.hstack((original,new_col))

print(original,"\n")
print(with_new_col,"\n")


[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2 3]
 [4 5 6]] 

[[ 1  2  3 11]
 [ 4  5  6 12]] 

