In [2]:
import numpy as np 

In [4]:
# Creating array from List
arr_id=np.array([1,2,3,4,5])
print("1 D array ", arr_id)

arr_2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2D Array ", arr_2d) 

arr_3d=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("2D Array ", arr_3d) 

1 D array  [1 2 3 4 5]
2D Array  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2D Array  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [19]:
arr=np.zeros([2,3])
print("Zero Array ,",arr)
arr=np.ones([2,3])
print("Ones Array ,",arr)


Zero Array , [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array , [[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
arr=np.arange(1,21)
print("1 to 20 ",arr)

1 to 20  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [11]:
arr = np.array([[3, 5, 7], [2, 4, 6]])
print("Shape ",arr.shape)
print("Shape ",arr.size)

Shape  (2, 3)
Shape  6


In [12]:
arr = np.array([1.0, 2.0, 3.0])
print("data type",arr.dtype)

data type float64


In [15]:
arr=np.arange(12)
print("reshape",arr.reshape(3,4))

reshape [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
# 6. Find mean, median, and standard deviation

arr = np.array([10, 20, 30, 40, 50])
print("mean",np.mean(arr))
print("median",np.median(arr))
print("standard",np.std(arr))


mean 30.0
median 30.0
standard 14.142135623730951


In [18]:
# 7. Create an identity matrix of size 4x4

identity=np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
# 8. Stack two arrays vertically and horizontally
a=np.array([[10,12],[13,14]])
b=np.array([[15,16],[17,18]])

print("Verticle ",np.vstack((a,b)))
print("horizontal ",np.hstack((a,b)))

Verticle  [[10 12]
 [13 14]
 [15 16]
 [17 18]]
horizontal  [[10 12 15 16]
 [13 14 17 18]]


In [22]:
a=np.array([1,2,3,45,69,75,2])
print(a.min())
print(a.max())

1
75


In [24]:
a=np.arange(1,11)
even=a[a%2==0]
print(even)

[ 2  4  6  8 10]


In [28]:
a=np.array([[1,2],[4,5]])
b=np.array([[7,8],[9,10]])
dot_product=np.dot(a,b)
print(dot_product)

[[25 28]
 [73 82]]


In [29]:
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
print(arr)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
matrix = np.random.rand(3, 3)
print("Matrix:\n", matrix)

det = np.linalg.det(matrix)
print("Determinant:", det)


Matrix:
 [[0.40649142 0.5356546  0.93826269]
 [0.70200451 0.48964472 0.90922213]
 [0.83689564 0.7686004  0.3028193 ]]
Determinant: 0.19169418464207286


In [31]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])
my_dot= np.dot(a, b)
print(my_dot)


[[ 4  4]
 [10  8]]


### Task 1: Load the Dataset
1. Load the CSV file using np.genfromtxt() or np.loadtxt() (skip the header if needed).
2. Slice out the numerical columns into a separate NumPy array (4 features only).
3. Print the shape of the resulting NumPy array.


In [ ]:
# import numpy as np

# # 1. Load the CSV file (skip the header if needed)
# data = np.genfromtxt('iris.csv', delimiter=',', skip_header=1)

# # 2. Slice out the numerical columns (first 4 features only)
# numerical_data = data[:, :4]  # assuming first 4 columns are numerical

# # 3. Print the shape of the resulting array
# print("Shape of numerical data:", numerical_data.shape)

# Ye function bhi text ya CSV file se data load karta hai, lekin zyada smart hai:

# Ye missing values ko handle kar sakta hai.

# Ye header ko skip kar sakta hai.

# Ye mixed data (jaise kuch columns text aur kuch numbers) bhi handle kar leta hai


Shape of numerical data: (149, 4)


In [ ]:
import numpy as np
data = np.genfromtxt('iris.csv', delimiter=',', skip_header=1)
print(data)
num

[[4.9 3.  1.4 0.2 nan]
 [4.7 3.2 1.3 0.2 nan]
 [4.6 3.1 1.5 0.2 nan]
 [5.  3.6 1.4 0.2 nan]
 [5.4 3.9 1.7 0.4 nan]
 [4.6 3.4 1.4 0.3 nan]
 [5.  3.4 1.5 0.2 nan]
 [4.4 2.9 1.4 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]
 [5.4 3.7 1.5 0.2 nan]
 [4.8 3.4 1.6 0.2 nan]
 [4.8 3.  1.4 0.1 nan]
 [4.3 3.  1.1 0.1 nan]
 [5.8 4.  1.2 0.2 nan]
 [5.7 4.4 1.5 0.4 nan]
 [5.4 3.9 1.3 0.4 nan]
 [5.1 3.5 1.4 0.3 nan]
 [5.7 3.8 1.7 0.3 nan]
 [5.1 3.8 1.5 0.3 nan]
 [5.4 3.4 1.7 0.2 nan]
 [5.1 3.7 1.5 0.4 nan]
 [4.6 3.6 1.  0.2 nan]
 [5.1 3.3 1.7 0.5 nan]
 [4.8 3.4 1.9 0.2 nan]
 [5.  3.  1.6 0.2 nan]
 [5.  3.4 1.6 0.4 nan]
 [5.2 3.5 1.5 0.2 nan]
 [5.2 3.4 1.4 0.2 nan]
 [4.7 3.2 1.6 0.2 nan]
 [4.8 3.1 1.6 0.2 nan]
 [5.4 3.4 1.5 0.4 nan]
 [5.2 4.1 1.5 0.1 nan]
 [5.5 4.2 1.4 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]
 [5.  3.2 1.2 0.2 nan]
 [5.5 3.5 1.3 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]
 [4.4 3.  1.3 0.2 nan]
 [5.1 3.4 1.5 0.2 nan]
 [5.  3.5 1.3 0.3 nan]
 [4.5 2.3 1.3 0.3 nan]
 [4.4 3.2 1.3 0.2 nan]
 [5.  3.5 1.6 0.6 nan]
 [5.1 3.8 1

### Task 2: Basic Array Operations
1. Compute the mean, max, and min for each column.
2. Calculate the standard deviation and variance for the dataset.
3. Normalize the data using Z-score normalization:
z=x−μσz = \frac{x - \mu}{\sigma}

In [8]:
import numpy as np

# Load the CSV file (specifically using dtype=float for numerical values)
data = np.genfromtxt('iris.csv', delimiter=',', skip_header=0, usecols=(0, 1, 2, 3), dtype=float)

# Verify data has been correctly loaded (first 5 rows)
print("Numerical data (first 5 rows):", data[:5])

# 1. Mean, Max, Min for each column
means = np.mean(data, axis=0)
max_vals = np.max(data, axis=0)
min_vals = np.min(data, axis=0)

print("Column-wise Mean:", means)
print("Column-wise Max:", max_vals)
print("Column-wise Min:", min_vals)

# 2. Standard Deviation and Variance
std_dev = np.std(data, axis=0)
variance = np.var(data, axis=0)

print("Standard Deviation:", std_dev)
print("Variance:", variance)

# 3. Z-score Normalization
z_normalized = (data - means) / std_dev

print("Z-score Normalized Data (first 5 rows):\n", z_normalized[:5])


Numerical data (first 5 rows): [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Column-wise Mean: [5.84333333 3.054      3.75866667 1.19866667]
Column-wise Max: [7.9 4.4 6.9 2.5]
Column-wise Min: [4.3 2.  1.  0.1]
Standard Deviation: [0.82530129 0.43214658 1.75852918 0.76061262]
Variance: [0.68112222 0.18675067 3.09242489 0.57853156]
Z-score Normalized Data (first 5 rows):
 [[-0.90068117  1.03205722 -1.3412724  -1.31297673]
 [-1.14301691 -0.1249576  -1.3412724  -1.31297673]
 [-1.38535265  0.33784833 -1.39813811 -1.31297673]
 [-1.50652052  0.10644536 -1.2844067  -1.31297673]
 [-1.02184904  1.26346019 -1.3412724  -1.31297673]]


### Task 3: Indexing and Slicing
1. Extract only the Sepal Length column.
2. Get the values for the first 10 flowers.
3. Extract flowers where Petal Length > 1.5

In [9]:
import numpy as np

# Load the CSV file 
data = np.genfromtxt('iris.csv', delimiter=',', skip_header=0, usecols=(0, 1, 2, 3), dtype=float)

# 1. Extract only the Sepal Length column (first column)
sepal_length = data[:, 0]  # First column (Sepal Length)
print("Sepal Length (first 5 rows):", sepal_length[:5])

# 2. Get the values for the first 10 flowers
first_10_flowers = data[:10, :]  # First 10 rows (all columns)
print("First 10 Flowers (features):\n", first_10_flowers)

# 3. Extract flowers where Petal Length > 1.5
petal_length_column = data[:, 2]  # Petal Length is the 3rd column (index 2)
flowers_with_petal_length_gt_1_5 = data[petal_length_column > 1.5, :]
print("Flowers with Petal Length > 1.5:\n", flowers_with_petal_length_gt_1_5)


Sepal Length (first 5 rows): [5.1 4.9 4.7 4.6 5. ]
First 10 Flowers (features):
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
Flowers with Petal Length > 1.5:
 [[5.4 3.9 1.7 0.4]
 [4.8 3.4 1.6 0.2]
 [5.7 3.8 1.7 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [5.1 3.8 1.6 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 

### Task 4: Advanced Operations
1. Find the Euclidean distance between the first two rows.
2. Count how many flowers have Sepal Width greater than the mean.
3. Multiply two columns element-wise (e.g., SepalLength * PetalLength).

In [10]:
import numpy as np

# Load the CSV file (assuming data is already loaded correctly)
data = np.genfromtxt('iris.csv', delimiter=',', skip_header=0, usecols=(0, 1, 2, 3), dtype=float)

# 1. Find the Euclidean distance between the first two rows
def euclidean_distance(row1, row2):
    return np.sqrt(np.sum((row1 - row2) ** 2))

# Extract first two rows
row1 = data[0, :]
row2 = data[1, :]

distance = euclidean_distance(row1, row2)
print(f"Euclidean distance between the first two rows: {distance}")

# 2. Count how many flowers have Sepal Width greater than the mean
sepal_width_column = data[:, 1]  # Sepal Width is the 2nd column (index 1)
mean_sepal_width = np.mean(sepal_width_column)

# Count how many values are greater than the mean
flowers_greater_than_mean = np.sum(sepal_width_column > mean_sepal_width)
print(f"Number of flowers with Sepal Width greater than the mean: {flowers_greater_than_mean}")

# 3. Multiply two columns element-wise (e.g., SepalLength * PetalLength)
sepal_length_column = data[:, 0]  # Sepal Length is the 1st column (index 0)
petal_length_column = data[:, 2]  # Petal Length is the 3rd column (index 2)

# Element-wise multiplication
sepal_petal_product = sepal_length_column * petal_length_column
print(f"Element-wise product of Sepal Length and Petal Length (first 5 rows): {sepal_petal_product[:5]}")


Euclidean distance between the first two rows: 0.5385164807134502
Number of flowers with Sepal Width greater than the mean: 67
Element-wise product of Sepal Length and Petal Length (first 5 rows): [7.14 6.86 6.11 6.9  7.  ]


### Task 5: Array Reshaping and Stacking
1. Reshape the array to simulate batches of size 30.
2. Stack two feature columns horizontally.
3. Create a boolean mask to filter rows with Petal Width < 0.5

In [11]:
import numpy as np

# Load the CSV file (assuming it's already loaded correctly)
data = np.genfromtxt('iris.csv', delimiter=',', skip_header=0, usecols=(0, 1, 2, 3), dtype=float)

# 1. Reshape the array to simulate batches of size 30
# We have 150 rows, so we can reshape the data to (5, 30, 4), where 5 is the number of batches, 30 is the batch size, and 4 is the number of features per row.
reshaped_data = np.reshape(data, (5, 30, 4))  # Shape will be (5, 30, 4)
print(f"Reshaped data to batches of size 30 (first batch):\n {reshaped_data[0]}")

# 2. Stack two feature columns horizontally (e.g., Sepal Length and Sepal Width)
sepal_length_column = data[:, 0]  # Sepal Length (1st column)
sepal_width_column = data[:, 1]   # Sepal Width (2nd column)

stacked_columns = np.column_stack((sepal_length_column, sepal_width_column))
print(f"Stacked Sepal Length and Sepal Width (first 5 rows):\n {stacked_columns[:5]}")

# 3. Create a boolean mask to filter rows with Petal Width < 0.5
petal_width_column = data[:, 3]  # Petal Width (4th column)

# Create a boolean mask
mask = petal_width_column < 0.5
filtered_data = data[mask, :]
print(f"Rows where Petal Width < 0.5 (first 5 rows):\n {filtered_data[:5]}")


Reshaped data to batches of size 30 (first batch):
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]]
Stacked Sepal Length and Sepal Width (first 5 rows):
 [[5.1 3.5]
 [4.9 3. ]
 [4.7 3.2]
 [4.6 3.1]
 [5.  3.6]]
Rows where Petal Width < 0.5 (first 5 rows):
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


BFS lab 

In [ ]:
import collections




def bfs(graph, root, goal):
    visited = set()
    queue = collections.deque([root])

    while queue:
        vertex = queue.popleft()
        if vertex == goal:
            print(f"Goal {goal} found!")
            return
        visited.add(vertex)
        for i in graph[vertex]:
            if i not in visited:
                queue.append(i)
    print(f"Goal {goal} not found.")

if __name__ == "__main__":
    graph = {0: [1, 2, 3], 1: [0, 2], 2: [0, 1, 4], 3: [0], 4: [2]}
    bfs(graph, 0, 4)  # Change 4 to any goal node you want



Goal 4 found!


### Sure! Here's a **NumPy Practical Quiz** to test your skills. It's a mix of hands-on coding tasks—just like you'd get in class or a practical exam.

---

## 🧪 NumPy Practical Quiz (Total Marks: 10)

### 🔸 Q1. Create a 1D NumPy array with numbers from 10 to 50 (inclusive). (1 mark)

---

### 🔸 Q2. Create a 3×3 NumPy array filled with random integers between 1 and 100. (1 mark)

---

### 🔸 Q3. Replace all even numbers in a NumPy array with -1. (2 marks)

Example input: `np.array([10, 15, 20, 25])`  
Expected output: `array([-1, 15, -1, 25])`

---

### 🔸 Q4. Given a 2D array, extract the second column. (2 marks)

```python
arr = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])
```

Expected output: `[10 25 40]`

---

### 🔸 Q5. Create a NumPy array of shape (4, 4) and find the sum of each row. (2 marks)

---

### 🔸 Q6. Reshape a 1D array of 12 elements into a 3x4 2D array. (2 marks)

---

## 📝 Instructions:
- Use `import numpy as np` at the start.
- Write clean code.
- Bonus if you print outputs with labels for clarity.

---

Would you like the **answer key** or prefer to try it first?

In [1]:
import numpy as np

In [3]:
data=np.array([10,12,20,30,40])
print(data)

[10 12 20 30 40]


In [114]:
### 🔸 Q2. Create a 3×3 NumPy array filled with random integers between 1 and 100. (1 mark)
# arr=np.arange(9).reshape(3,3)
arr2=np.random.randint(1,100,(3,3))
print(arr2)

[[18 15 99]
 [20 41 48]
 [31  6 60]]


In [107]:
### 🔸 Q4. Given a 2D array, extract the second column. (2 marks)
arr = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])
print(arr[:,1])

# Expected output: `[10 25 40]`



[10 25 40]


In [67]:
### 🔸 Q5. Create a NumPy array of shape (4, 4) and find the sum of each row. (2 marks)
data=np.arange(16).reshape(4,4)
data2=sum(data)
print(data2)

[24 28 32 36]


In [42]:
### 🔸 Q6. Reshape a 1D array of 12 elements into a 3x4 2D array. (2 marks)
arr=np.arange(12)
arr2=arr.reshape(3,4)
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
arr=np.arange(9)
print(arr)

[0 1 2 3 4 5 6 7 8]


In [5]:
arr2=np.ones((3,3))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
arr3=np.eye(5,5)
print(arr3)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
arr4=np.random.random(1,10)
print(arr4)

TypeError: random() takes at most 1 positional argument (2 given)