🔷 NumPy – Intermediate Level Practice
### ✅ Task 1: Broadcasting with Array Operations
Create a 2D array of shape (4, 3) with random integers from 1 to 20.
Then create a 1D array:

python
Copy
Edit
b = np.array([1, 2, 3])
Now add b to each row of the 2D array using broadcasting.



In [1]:
import numpy as np 


In [6]:
arr = np.random.randint(1,21,size=(4,3))
b = np.array([1,2,3])
print(arr)
add = arr + b
print(add)

[[16  9  4]
 [ 5 12  3]
 [12  6  7]
 [20  7 15]]
[[17 11  7]
 [ 6 14  6]
 [13  8 10]
 [21  9 18]]


### ✅ Task 2: Fancy Indexing & Boolean Masking
From the array:

python
Copy
Edit
arr = np.array([5, 12, 7, 9, 20, 13])
Get elements greater than 10.

Get elements at indices [1, 3, 4] using fancy indexing.



In [38]:
arr =np.array([5, 12, 7, 9, 20, 13])
df = arr [arr >= 10]
# arr[::,1:3:7]
# # for i in arr:
# #     if i >= 10:
# #         print(i)
        
# # print(len(arr))
for i in range(len(arr)):
    # print(i)
    if i == 1:
        print(arr[i])
    elif i ==3:
        print(arr[i])
    elif i == 4:
        print(arr[i])

12
9
20


✅ Task 3: Matrix Multiplication (Dot Product of 2D arrays)
Create two 2D arrays A and B, each of size (3x3) with any values.
Then:

Perform matrix multiplication using np.dot() or @ operator.



In [40]:
a = np.random.randint(1,11,size=(3,3))
b = np.random.randint(1,11,size=(3,3))
print(a)
print(b)
print()
print()
np.dot(a,b)

[[ 2  6  5]
 [ 2  3 10]
 [ 8  5  6]]
[[ 4  5  8]
 [ 8 10  3]
 [ 4  3  8]]




array([[ 76,  85,  74],
       [ 72,  70, 105],
       [ 96, 108, 127]], dtype=int32)

### ✅ Task 4: Reshaping & Flattening
Create a 1D array of 12 elements.
Then:

Reshape it into (3, 4)

Flatten it back to 1D using .flatten() and .ravel() and show the difference



In [49]:
d1 = np.random.randint(1,13,12)
print(d1)
re=d1.reshape(3,4)
print(re)
fla=re.flatten()
print(fla)
re.ravel()

[10 10  9  7 10  5 10 12  2 11 12 10]
[[10 10  9  7]
 [10  5 10 12]
 [ 2 11 12 10]]
[10 10  9  7 10  5 10 12  2 11 12 10]


array([10, 10,  9,  7, 10,  5, 10, 12,  2, 11, 12, 10], dtype=int32)

### ✅ Task 5: Statistical Operations
Create a 5x5 array with values from 1 to 25.
Now calculate:

Mean

Median

Standard Deviation

Variance



In [58]:
ar = np.random.randint(1,101,size=(5,5))

print(ar)

for i in ar:
    print(i.mean())
    # print(i.median())
    print(i.std())
    print(i.var(),"\n")


[[25 25 37  2 66]
 [79 17 65  5 71]
 [75 83 54 18 71]
 [76 10 24  1 78]
 [91 58 31  5  6]]
31.0
20.851858430365386
434.8 

47.4
30.28927202822808
917.4399999999999 

60.2
23.12920232087566
534.9599999999999 

37.8
32.84143724016962
1078.56 

38.2
32.774380238228765
1074.16 

